//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cloth_of_products
    {
        public int Id_cloth_of_products { get; set; }
        public Nullable<int> Article_of_cloth { get; set; }
        public Nullable<int> ID_Product { get; set; }
    
        public virtual Cloth Cloth { get; set; }
        public virtual The_product The_product { get; set; }
    }
}
