//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Furniture_of_product
    {
        public int id_FoP { get; set; }
        public Nullable<int> Article_of_furniture { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Hight { get; set; }
        public string Fabric { get; set; }
        public string Edging { get; set; }
        public string Hardware { get; set; }
        public string Placements { get; set; }
        public string HardwareSizes { get; set; }
    
        public virtual Furniture Furniture { get; set; }
        public virtual The_product The_product { get; set; }
    }
}
