//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Furniture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Furniture()
        {
            this.Furniture_of_product = new HashSet<Furniture_of_product>();
            this.Warehouse_of_furniture = new HashSet<Warehouse_of_furniture>();
        }
    
        public int Article_of_furniture { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<int> Hight { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Furniture_of_product> Furniture_of_product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warehouse_of_furniture> Warehouse_of_furniture { get; set; }
    }
}
