//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordered_products
    {
        public int Order_number { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual The_product The_product { get; set; }
    }
}
