//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse_of_furniture
    {
        public int Batch { get; set; }
        public Nullable<int> Article_of_furniture { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Furniture Furniture { get; set; }
    }
}
